# Generated by Django 4.2.7 on 2024-03-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companys', '0008_hiring_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', null=True)),
                ('dob', models.TextField(db_column='dob', null=True)),
                ('email', models.TextField(db_column='email', null=True)),
                ('mob', models.TextField(db_column='mob', null=True)),
                ('password', models.TextField(db_column='password', null=True)),
            ],
            options={
                'db_table': 'jobseeker_signup',
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.TextField(max_length=100, null=True)),
                ('name', models.TextField(db_column='name', max_length=100, null=True)),
                ('dob', models.TextField(db_column='dob', max_length=100, null=True)),
                ('email', models.TextField(db_column='email', max_length=100, null=True)),
                ('mob', models.TextField(db_column='mob', max_length=100, null=True)),
                ('quali', models.TextField(db_column='quali', max_length=100, null=True)),
                ('cv', models.FileField(db_column='cv', null=True, upload_to='resumes/')),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companys.companys')),
            ],
        ),
    ]
