# Generated by Django 4.2.7 on 2024-01-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', null=True)),
                ('dob', models.TextField(db_column='dob', null=True)),
                ('em', models.TextField(db_column='email', null=True)),
                ('mob', models.TextField(db_column='mob', null=True)),
                ('quali', models.TextField(db_column='quali', null=True)),
                ('cv', models.TextField(db_column='cv', null=True)),
            ],
        ),
    ]
