# Generated by Django 4.2.7 on 2024-01-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.TextField(db_column='cv', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='dob',
            field=models.TextField(db_column='dob', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='em',
            field=models.TextField(db_column='email', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='mob',
            field=models.TextField(db_column='mob', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.TextField(db_column='name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='quali',
            field=models.TextField(db_column='quali', max_length=100, null=True),
        ),
    ]
