# Generated by Django 4.2.7 on 2024-01-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_alter_apply_cv_alter_apply_dob_alter_apply_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='em',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.ImageField(db_column='cv', null=True, upload_to=''),
        ),
    ]
