# Generated by Django 4.2.7 on 2024-01-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_rename_em_apply_email_alter_apply_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(db_column='cv', null=True, upload_to='resumes/'),
        ),
    ]
