# Generated by Django 4.2.7 on 2024-01-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companys',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='password',
        ),
        migrations.AddField(
            model_name='companys',
            name='exp',
            field=models.TextField(db_column='exp', null=True),
        ),
        migrations.AddField(
            model_name='companys',
            name='job',
            field=models.TextField(db_column='job', null=True),
        ),
        migrations.AddField(
            model_name='companys',
            name='quali',
            field=models.TextField(db_column='quali', null=True),
        ),
        migrations.AlterModelTable(
            name='companys',
            table=None,
        ),
    ]
