# Generated by Django 4.2.7 on 2024-01-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_remove_companys_dob_remove_companys_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', null=True)),
                ('job', models.TextField(db_column='job', null=True)),
                ('quali', models.TextField(db_column='quali', null=True)),
                ('exp', models.TextField(db_column='exp', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companys',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='job',
        ),
        migrations.RemoveField(
            model_name='companys',
            name='quali',
        ),
        migrations.AddField(
            model_name='companys',
            name='dob',
            field=models.TextField(db_column='dob', null=True),
        ),
        migrations.AddField(
            model_name='companys',
            name='email',
            field=models.TextField(db_column='email', null=True),
        ),
        migrations.AddField(
            model_name='companys',
            name='mob',
            field=models.TextField(db_column='mob', null=True),
        ),
        migrations.AddField(
            model_name='companys',
            name='password',
            field=models.TextField(db_column='password', null=True),
        ),
        migrations.AlterModelTable(
            name='companys',
            table='companys_signup',
        ),
    ]
