# Generated by Django 4.2.7 on 2024-01-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0003_hiring_remove_companys_exp_remove_companys_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companys.companys'),
        ),
    ]
