# Generated by Django 4.2.7 on 2024-01-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0004_hiring_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiring',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='hiring',
            name='name',
        ),
    ]
