# Generated by Django 4.2.7 on 2024-01-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0005_remove_hiring_comp_remove_hiring_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='skills',
            field=models.TextField(db_column='skills', null=True),
        ),
    ]
