# Generated by Django 4.2.7 on 2024-03-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0007_hiring_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='company_name',
            field=models.ForeignKey(db_column='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='companys.companys'),
        ),
    ]
